// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package datenmodell;

import lombok.Getter;
import lombok.Setter;

@Getter
@Setter
public class Ergebnis {

	private int Punkte;

	private Spielrunde spielrunde;

	private Spieler spieler;
};
