// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package datenmodell;

import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;

import lombok.Getter;
import lombok.Setter;

@Getter
@Setter
@Entity
public class Ergebnis extends BaseEntity{

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	@Column
	private int Punkte;

	@ManyToOne
	private Spielrunde spielrunde;

	@ManyToMany
    @JoinTable(
            name = "ergebnis_spieler",
            joinColumns = @JoinColumn(name = "ergebnis_id"),
            inverseJoinColumns = @JoinColumn(name = "spieler_id")
        )
	private List<Spieler> spieler;
};
