// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package datenmodell;

/************************************************************/
/**
 * 
 */
public class Person {
	/**
	 * 
	 */
	public int id;
	/**
	 * 
	 */
	public int Gewinne;
	/**
	 * 
	 */
	public int Verluste;
	/**
	 * 
	 */
	public String Name;
	/**
	 * 
	 */
	public Spieler[] spieler;
};
