// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package datenmodell;

import java.util.List;

import javax.persistence.Entity;
import javax.persistence.OneToMany;

import lombok.Getter;
import lombok.Setter;

@Getter
@Setter
@Entity
public class Person extends BaseEntity{

	private int Gewinne;

	private int Verluste;

	private String Name;

	@OneToMany
	private List<Spieler> spielerListe;
};
