// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package datenmodell;

import java.util.List;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.OneToMany;

import lombok.Getter;
import lombok.Setter;

@Getter
@Setter
@Entity
public class Person extends BaseEntity{

	@Column
	private int Gewinne;

	@Column
	private int Verluste;

	@Column
	private String Name;

	@OneToMany(cascade = CascadeType.ALL, mappedBy="person", orphanRemoval = true)
	private List<Spieler> spielerListe;
};
