// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package datenmodell;

import lombok.Getter;
import lombok.Setter;

@Getter
@Setter
public class Regel {

	private int id;

	private String Beschreibung;

	private Spielkarte spielkarte;
};
