// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package datenmodell;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.OneToMany;

import lombok.Getter;
import lombok.Setter;

@Getter
@Setter
@Entity
public class Spiel extends BaseEntity{

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	@Column
	private Date Datum;
	
	@Column
	private long beginn;

	@Column
	private long ende;
	
	@Column
	private long dauer;

	@OneToMany
	private List<Spieler> spielerListe;
	
	
	public Spiel() {
		this.Datum = new Date();
	}
	
	public void registriereSpieler(Spieler spieler) {
		if (this.spielerListe == null) {
			this.spielerListe = new ArrayList<Spieler>();
		}
		this.spielerListe.add(spieler);
	}
	
	public Spielrunde erstelleRunde() {
		return new Spielrunde();
	}
};
