// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package datenmodell;

import java.util.Date;

/************************************************************/
/**
 * 
 */
public class Spiel {
	/**
	 * 
	 */
	public int id;
	/**
	 * 
	 */
	public Date Datum;
	/**
	 * 
	 */
	public float Dauer;
	/**
	 * 
	 */
	public Spieler[] spieler;
};
