// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package datenmodell;


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.ManyToOne;
import javax.persistence.OneToOne;

import lombok.Getter;
import lombok.Setter;

/************************************************************/
/**
 * 
 */
@Getter
@Setter
@Entity
public class Spielkarte extends BaseEntity {
	
	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	@Column
	private Blattwert Blattwert;

	@Column
	private Blatttyp Blatttyp;

	@OneToOne
	private Zug zug;

	@ManyToOne
	private Spieler spieler;
	

	public Spielkarte(Blatttyp blatttyp, Blattwert blattwert) {
		this.Blatttyp = blatttyp;
		this.Blattwert = blattwert;
	}
	

};
