// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package datenmodell;

import java.util.ArrayList;
import java.util.Collections;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;

import lombok.Getter;
import lombok.Setter;

/************************************************************/
/**
 * 
 */

@Setter
@Getter
@Entity
public class Spielrunde extends BaseEntity{

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	@Column
	private int nummer;

	@Column
	private int gewinnerId;
	
	@ManyToOne
	@JoinColumn(name="spiel_id")
	private Spiel spiel;

	@OneToMany
	private List<Spielkarte> gespielteKarteListe;

	@OneToMany
	private List<Spielkarte> stapel;

	public void mischeGespielteKarte() {

		if (this.stapel.size() == 0) {
			Collections.shuffle(this.gespielteKarteListe);
			this.stapel.addAll(this.gespielteKarteListe);
		}
	}

	public void baueStapel(boolean includeJokers) {
		this.stapel = new ArrayList<Spielkarte>();
		for (Blatttyp blatttyp : Blatttyp.values()) {
			for (Blattwert blattwert : Blattwert.values()) {
				if (blattwert == Blattwert.Joker && !includeJokers) {
					continue;
				}
				stapel.add(new Spielkarte(blatttyp, blattwert));
			}
		}

	}
};
