// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package datenmodell;


import lombok.Getter;
import lombok.Setter;

/************************************************************/
/**
 * 
 */
@Getter
@Setter
public class Spielkarte {

	private int id;

	private Blattwert Blattwert;

	private Blatttyp Blatttyp;

	private Zug zug;

	private Spieler spieler;
	

	public Spielkarte(Blatttyp blatttyp, Blattwert blattwert) {
		this.Blatttyp = blatttyp;
		this.Blattwert = blattwert;
	}
	

};
