// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package datenmodell;

import java.util.ArrayList;
import java.util.List;

import javax.persistence.Entity;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;

import lombok.Getter;
import lombok.Setter;

@Getter
@Setter
@Entity
public class Spieler extends BaseEntity{

	
	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	@ManyToOne
	private Spiel spiel;

	@OneToMany
	private List<Spielkarte> handKarten;
	

	public void zieheSpielkarte(Spielkarte spielkarte) {
		if(this.handKarten == null) {
			this.handKarten = new ArrayList<Spielkarte>();
		}
		this.handKarten.add(spielkarte);
	}
	
	public void legeKarteAuf(Spielkarte spielkarte, Spielrunde spielrunde) {
		spielrunde.getGespielteKarteListe().add(spielkarte);
	}
	
};
