// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package datenmodell;

/************************************************************/
/**
 * 
 */
public class Spielrunde {
	/**
	 * 
	 */
	public int nummer;
	/**
	 * 
	 */
	public int gewinnerId;
	/**
	 * 
	 */
	public Spielkarte[] gespielteKarteListe;
	/**
	 * 
	 */
	public Spielkarte[] stapelKarteListe;
	/**
	 * 
	 */
	public Spiel spiel;
	/**
	 * 
	 */
	public Zug[] zug;

	/**
	 * 
	 */
	public void mischeGespielteKarte() {
	}
};
