// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package datenmodell;

import java.util.Collections;
import java.util.List;

import lombok.Getter;
import lombok.Setter;

/************************************************************/
/**
 * 
 */
@Getter
@Setter
public class Spielrunde {
	/**
	 * 
	 */
	public int nummer;
	/**
	 * 
	 */
	public int gewinnerId;
	/**
	 * 
	 */
	public List<Spielkarte> gespielteKarteListe;
	/**
	 * 
	 */
	public List<Spielkarte> stapel;
	/**
	 * 
	 */
	public Spiel spiel;
	/**
	 * 
	 */
	public List<Zug> zuege;

	/**
	 * 
	 */
	public void mischeGespielteKarte() {
		
		if(this.stapel.size() == 0) {
			Collections.shuffle(this.gespielteKarteListe);
			this.stapel.addAll(this.gespielteKarteListe);
		}
	}
	
	
	public void baueStapel() {
		
		for(Blatttyp blatttyp: datenmodell.Blatttyp.values()) {
			for(Blattwert blattwert: datenmodell.Blattwert.values()) {
				stapel.add(new Spielkarte(blatttyp, blattwert));
			}
		}
	}
};
