// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package datenmodell;


import javax.persistence.Entity;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;

import lombok.Getter;
import lombok.Setter;

/************************************************************/
/**
 * 
 */
@Getter
@Setter
@Entity
public class Spielkarte extends BaseEntity {
	
    public final static int SPADES = 0;   // Codes for the 4 suits, plus Joker.
    public final static int HEARTS = 1;
    public final static int DIAMONDS = 2;
    public final static int CLUBS = 3;
    public final static int JOKER = 4;

    public final static int ACE = 1;      // Codes for the non-numeric cards.
    public final static int JACK = 11;    //   Cards 2 through 10 have their 
    public final static int QUEEN = 12;   //   numerical values for their codes.
    public final static int KING = 13;

	private int id;

	private Blattwert Blattwert;

	private Blatttyp Blatttyp;

	@OneToOne
	private Zug zug;

	@OneToMany
	private Spieler spieler;
	

	public Spielkarte(Blatttyp blatttyp, Blattwert blattwert) {
		this.Blatttyp = blatttyp;
		this.Blattwert = blattwert;
	}
	

};
