// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package datenmodell;

import java.util.List;

import javax.persistence.Entity;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;

import lombok.Getter;
import lombok.Setter;

/************************************************************/
/**
 * 
 */	
@Getter
@Setter
@Entity
public class Zug extends BaseEntity{

	private Richtung richtung;

	@OneToOne
	private Spielkarte aufgelegteKarte;

	@OneToMany
	private List<Spielkarte> erlaubteNaechsteKarten;
	

	public void bestimmeErlaubteNaechsteKarten() {
		
		// Normale erlaubte Karten
		
		
	
		// Sonderregel-Karten
	}
	

};
