// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package datenmodell;

/************************************************************/
/**
 * 
 */
public class Zug {
	/**
	 * 
	 */
	public Richtung richtung;
	/**
	 * 
	 */
	public Spielkarte aufgelegteKarte;
	/**
	 * 
	 */
	public Spielkarte[] erlaubteNaechsteKarten;

};
