// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package neuesDatenmodell;

import java.util.List;

import lombok.Getter;
import lombok.Setter;

@Getter
@Setter
public class Spielrunde{


	private String gewinnerName;
	
	private long dauer;
	
	// Stapel mit verdeckten karten
	private KartenStapel stapel;
	
	// Stapel mit aufgelegten Karten
	private KartenStapel stapelAufgelegt;
	
	private KartenHand handDaran;
	
	private List<Ergebnis> ergebnisse;


};
