// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package datenmodel.Enum;


public enum Blatttyp {

	Pik,

	Herz,

	Karo,

	Kreuz;
};
