// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package datenmodel;

import datenmodel.Enum.Blatttyp;
import datenmodel.HilfKlassen.BaseEntity;
import lombok.Getter;
import lombok.Setter;

import javax.persistence.*;
import java.util.Date;
import java.util.List;

@Getter
@Setter
@Entity
public class Spielrunde extends BaseEntity {

    @Column
    private String gewinnerName;

    @Column
    private Date start;

    @Column
    private long dauer;

    // Stapel mit verdeckten karten
    @Embedded
    private List<Spielkarte> verdeckteStapel;

    // Stapel mit aufgelegten Karten
    @Embedded
    private List<Spielkarte> aufgelegtStapel;

    @OneToMany
    private List<Ergebnis> ergebnisListe;

    @OneToMany
    private List<Spieler> spielerListe;

    @Column
    @Enumerated(EnumType.STRING)
    private Blatttyp rundeFarbe;

    @Column
    private Integer zuZiehnKartenAnzahl;

}
