@startuml

[SpielregelManagement] as srlm

[SpielerZugMagnagement] as szm

[SpielManagement] as sm

[BrettManagement] as bm

[Frontend] as frontend

database "maumauDB" {

}


ISpielRegelMgmt - srlm

ISpielerZugMgmt - szm

ISpielMgmt - sm

IBrettMgmt - bm


sm -down-> ISpielRegelMgmt

sm --> maumauDB

bm -right-> ISpielerZugMgmt


frontend -right-> IBrettMgmt

frontend --> ISpielMgmt

bm --> ISpielMgmt

@enduml